import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Edit, Trash2, Play, Star } from "lucide-react";
export function TemplatesList({ templates, isLoading, onEdit, onDelete, onUse }) {
    if (isLoading) {
        return (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [...Array(6)].map((_, i) => (_jsxs(Card, { className: "animate-pulse", children: [_jsxs(CardHeader, { children: [_jsx("div", { className: "h-6 bg-gray-200 rounded w-3/4" }), _jsx("div", { className: "h-4 bg-gray-200 rounded w-1/2" })] }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "h-4 bg-gray-200 rounded" }), _jsx("div", { className: "h-4 bg-gray-200 rounded w-2/3" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("div", { className: "h-8 bg-gray-200 rounded w-16" }), _jsx("div", { className: "h-8 bg-gray-200 rounded w-16" })] })] }) })] }, i))) }));
    }
    return (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: templates.map((template) => (_jsxs(Card, { className: "hover:shadow-lg transition-shadow", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsxs(CardTitle, { className: "text-lg flex items-center gap-2", children: [template.name, template.isDefault && (_jsx(Star, { className: "h-4 w-4 text-yellow-500 fill-current" }))] }), _jsx("p", { className: "text-sm text-gray-600 mt-1", children: template.label })] }), _jsx(Badge, { variant: "outline", className: "text-xs", children: template.currency })] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("p", { className: "text-2xl font-bold text-green-600", children: [template.amount, " ", template.currency] }), template.message && (_jsx("p", { className: "text-sm text-gray-500 mt-1", children: template.message }))] }), _jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { size: "sm", onClick: () => onUse(template), className: "flex-1", children: [_jsx(Play, { className: "h-4 w-4 mr-1" }), "Use"] }), !template.isDefault && (_jsxs(_Fragment, { children: [_jsx(Button, { size: "sm", variant: "outline", onClick: () => onEdit(template), children: _jsx(Edit, { className: "h-4 w-4" }) }), _jsx(Button, { size: "sm", variant: "outline", onClick: () => onDelete(template.id), className: "text-red-600 hover:text-red-700", children: _jsx(Trash2, { className: "h-4 w-4" }) })] }))] })] }) })] }, template.id))) }));
}
