import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, TrendingUp, DollarSign, CreditCard } from "lucide-react";
import { MetricsCards } from "@/components/dashboard/metrics-cards";
import { RecentPayments } from "@/components/dashboard/recent-payments";
export function AnalyticsPage({ onBack, userId }) {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: onBack, className: "flex items-center gap-2", children: [_jsx(ArrowLeft, { className: "h-4 w-4" }), "Back to Dashboard"] }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Analytics" }), _jsx("p", { className: "text-gray-600", children: "Track your payment performance and insights" })] })] }), _jsx(MetricsCards, { userId: userId }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(TrendingUp, { className: "h-5 w-5 text-blue-600" }), "Payment Trends"] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(TrendingUp, { className: "h-12 w-12 mx-auto mb-4 text-gray-300" }), _jsx("p", { children: "Payment trend charts coming soon" })] }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(DollarSign, { className: "h-5 w-5 text-green-600" }), "Revenue Breakdown"] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(DollarSign, { className: "h-12 w-12 mx-auto mb-4 text-gray-300" }), _jsx("p", { children: "Revenue analytics coming soon" })] }) })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(CreditCard, { className: "h-5 w-5 text-purple-600" }), "Recent Payments"] }) }), _jsx(CardContent, { children: _jsx(RecentPayments, { userId: userId }) })] })] }));
}
